### ISSUE TITLE
Непонятный import 

### ISSUE THREAD

**Issue by svedete1** [Larionov-VA/PhysicsLabTools#3]
не совсем понятно откуда берется этот импорт, нет файла или библиотеки с таким названием
@Larionov-VA 
https://github.com/Larionov-VA/PhysicsLabTools/blame/48204558a9b2003cf804a376b1c8d1466558a7cd/run_PLtools.py#L9

**Comment by Larionov-VA** [comment]
Да, поторопился, импортировал модуль, который тестирую, но еще не залил в репозиторий 
@svedete1 Исправлено
