### ISSUE TITLE
Проблема с вводом внутри функции не позволяющая создать интерфейс

### ISSUE THREAD

**Issue by svedete1** [Larionov-VA/PhysicsLabTools#7]
https://github.com/Larionov-VA/PhysicsLabTools/blame/94cef370a0f7eea643bf8118922cbab8555e2cae/make_docx.py#L70-L71
Вызов ввода внутри функции мешает использованию данной функции при создании интерфейса для программы. Так как консоль не используется при использовании интерфйеса, но программа ожидает ввод и происходит зависание интерфейса

@PlestoPG Можешь, пожалуйста, каким-либо образом вынести ввод переменных за пределы функции, пусть функция принимает их как аргументы и т. п.

**Comment by svedete1** [comment]
Да и в принципе интерфейс поломали так как в [run_PLtools.py](https://github.com/Larionov-VA/PhysicsLabTools/blob/main/run_PLtools.py) вызывается создание файла внутри функции которая в интерфейсе используется

**Comment by PlestoPG** [comment]
Отправил Pull Request
